/**
 * dsp_mfcc.c
 * ==========
 * On-device DSP + MFCC pipeline. Zephyr/nRF52840 version.
 *
 * Key differences from the desktop mfcc_core.c / bandpass_sos.c:
 *   - NO malloc/free. All buffers are static.
 *   - CMSIS-DSP is used via Zephyr's module (arm_math.h from Zephyr SDK).
 *   - Bandpass SOS coefficients are for 8 kHz (not 2 kHz).
 *   - Bandpass filter state is persistent across half-buffers during
 *     one recording (not reset per-frame like the desktop version).
 *   - The decimated int16 buffer is 40 KB — it must be declared here so
 *     it sits in BSS, not on any thread stack.
 *
 * v6.3 STREAMING CHANGE:
 *   - Removed g_mfcc_out[1331][20] (104 KB BSS).
 *   - Removed dsp_mfcc_run() batch API.
 *   - Added dsp_mfcc_reset() + dsp_mfcc_feed_chunk() + dsp_mfcc_finish().
 *   - dsp_mfcc_finish() uses a single s_mfcc_frame[20] scratch buffer (80 B)
 *     and invokes the caller's callback once per frame.
 *
 * SOS COEFFICIENTS
 * ----------------
 * These are Butterworth-4 bandpass 10–200 Hz @ 8000 Hz.
 * Generated by: scipy.signal.butter(4, [10,200], btype='band', fs=8000, output='sos')
 * CMSIS sign convention: feedback coefficients are NEGATED (-a1, -a2).
 *
 * If you need to regenerate, run on the laptop:
 *   python - <<'EOF'
 *   from scipy.signal import butter
 *   import numpy as np
 *   sos = butter(4, [10, 200], btype='band', fs=8000, output='sos')
 *   for s in sos:
 *       b0,b1,b2,a0,a1,a2 = s
 *       print(f"  {b0:.10f}f, {b1:.10f}f, {b2:.10f}f,  {-a1:.10f}f, {-a2:.10f}f,")
 *   EOF
 */

#include "dsp_mfcc.h"
#include <arm_math.h>
#include <string.h>
#include <math.h>
#include <zephyr/logging/log.h>

LOG_MODULE_REGISTER(dsp_mfcc);

/* ══════════════════════════════════════════════════════════════════
 * SECTION 1: BANDPASS FILTER
 * 10–200 Hz Butterworth-4, at 8000 Hz.
 * ══════════════════════════════════════════════════════════════════ */

#define BP_N_STAGES   4   /* 4th-order bandpass → 4 biquad sections */

/*
 * CMSIS biquad coefficients: [b0, b1, b2, -a1, -a2] per section.
 *
 * Generated by scipy: butter(4, [10, 200], btype='band', fs=8000, output='sos')
 * CMSIS sign convention: feedback coefficients are NEGATED (-a1, -a2).
 *
 * NOTE: The previous values were placeholders that attenuated the passband
 * by 40–70 dB, causing the MFCC log-mel output to saturate at the 1e-6 floor
 * (c0 ≈ -61.78 across all frames). These are the real coefficients.
 */
static const float32_t s_bp_coeffs[BP_N_STAGES * 5] = {
    /* section 0: b0,            b1,            b2,            -a1,           -a2          */
    +0.0000256870f, +0.0000513741f, +0.0000256870f, +1.7521353989f, -0.7703674421f,
    /* section 1 */
    +1.0000000000f, +2.0000000000f, +1.0000000000f, +1.8745313518f, -0.8973206556f,
    /* section 2 */
    +1.0000000000f, -2.0000000000f, +1.0000000000f, +1.9844767549f, -0.9845500024f,
    /* section 3 */
    +1.0000000000f, -2.0000000000f, +1.0000000000f, +1.9943824564f, -0.9944455175f,
};

/* State: 2 state variables per section, DF2T form */
static float32_t s_bp_state[BP_N_STAGES * 2];
static arm_biquad_cascade_df2T_instance_f32 s_bp_inst;

/* ══════════════════════════════════════════════════════════════════
 * SECTION 2: DECIMATED BUFFER
 * 10 s × 2000 Hz = 20000 int16 samples → 40 KB in BSS.
 * ══════════════════════════════════════════════════════════════════ */
static int16_t  s_decimated[DECIMATED_SAMPLES];
static int       s_dec_idx;   /* write cursor, reset by dsp_mfcc_reset() */

/* ══════════════════════════════════════════════════════════════════
 * SECTION 3: MFCC CONSTANTS (computed once at init)
 * ══════════════════════════════════════════════════════════════════ */

/* Periodic Hamming window: w[n] = 0.54 - 0.46*cos(2πn/N), divisor N */
static float32_t s_hamming[MFCC_FRAME_SAMPLES];

/* Mel filterbank: [N_MEL][N_FFT_BINS] row-major */
static float32_t s_mel_fb[MFCC_N_MEL * MFCC_N_FFT_BINS];

/* Orthonormal DCT-II matrix: [N_MFCC][N_MEL] row-major */
static float32_t s_dct[MFCC_N_MFCC * MFCC_N_MEL];

/* ══════════════════════════════════════════════════════════════════
 * SECTION 4: SCRATCH BUFFERS (reused every frame / every chunk)
 *
 * s_bp_scratch  — float32 version of one SAADC half-buffer (512 samples, 2 KB)
 * s_fft_in      — windowed + zero-padded frame              (512 floats,  2 KB)
 * s_fft_out     — RFFT complex output                       (512 floats,  2 KB)
 * s_power       — Re²+Im² power spectrum                    (257 floats,  1 KB)
 * s_mel         — mel filterbank energies                   (20  floats, 80  B)
 * s_mfcc_frame  — one frame of MFCC output (replaces g_mfcc_out) (20 floats, 80 B)
 *
 * Total scratch: ~7 KB  (was 104 KB + 7 KB before)
 * ══════════════════════════════════════════════════════════════════ */
#define BP_SCRATCH_MAX  512
static float32_t s_bp_scratch[BP_SCRATCH_MAX];

static float32_t s_fft_in[MFCC_FFT_SIZE];
static float32_t s_fft_out[MFCC_FFT_SIZE];
static float32_t s_power[MFCC_N_FFT_BINS];
static float32_t s_mel[MFCC_N_MEL];
static float32_t s_mfcc_frame[MFCC_N_MFCC];   /* single-frame output, 80 bytes */

/* CMSIS-DSP RFFT instance */
static arm_rfft_fast_instance_f32 s_rfft;

/* ══════════════════════════════════════════════════════════════════
 * INTERNAL: build Hamming window
 * ══════════════════════════════════════════════════════════════════ */
static void build_hamming(void)
{
    for (int i = 0; i < MFCC_FRAME_SAMPLES; i++) {
        s_hamming[i] = 0.54f - 0.46f * cosf(
            2.0f * 3.14159265f * (float)i / (float)MFCC_FRAME_SAMPLES);
    }
}

/* ══════════════════════════════════════════════════════════════════
 * INTERNAL: build HTK mel filterbank
 * Matches mfcc_core.c build_mel_filterbank() exactly.
 * f_low=10 Hz, f_high=TARGET_RATE/2=1000 Hz.
 * ══════════════════════════════════════════════════════════════════ */
static float hz_to_mel(float hz) { return 2595.0f * log10f(1.0f + hz / 700.0f); }
static float mel_to_hz(float mel) { return 700.0f * (powf(10.0f, mel / 2595.0f) - 1.0f); }

static void build_mel_filterbank(void)
{
    const float f_low  = 10.0f;
    const float f_high = (float)DSP_TARGET_RATE / 2.0f;  /* 1000 Hz */
    const float mel_lo = hz_to_mel(f_low);
    const float mel_hi = hz_to_mel(f_high);

    float mel_pts[MFCC_N_MEL + 2];
    float hz_pts [MFCC_N_MEL + 2];
    float bin_pts[MFCC_N_MEL + 2];

    for (int i = 0; i < MFCC_N_MEL + 2; i++) {
        mel_pts[i] = mel_lo + (float)i * (mel_hi - mel_lo) / (float)(MFCC_N_MEL + 1);
        hz_pts[i]  = mel_to_hz(mel_pts[i]);
        bin_pts[i] = hz_pts[i] / ((float)DSP_TARGET_RATE / 2.0f) * (float)(MFCC_N_FFT_BINS - 1);
    }

    memset(s_mel_fb, 0, sizeof(s_mel_fb));

    for (int m = 0; m < MFCC_N_MEL; m++) {
        float f_left   = bin_pts[m];
        float f_center = bin_pts[m + 1];
        float f_right  = bin_pts[m + 2];
        float *row     = s_mel_fb + m * MFCC_N_FFT_BINS;

        for (int k = 0; k < MFCC_N_FFT_BINS; k++) {
            float kf  = (float)k;
            float val = 0.0f;
            if (kf >= f_left && kf <= f_center) {
                float d = f_center - f_left;
                val = (d > 0.0f) ? (kf - f_left) / d : 0.0f;
            } else if (kf > f_center && kf <= f_right) {
                float d = f_right - f_center;
                val = (d > 0.0f) ? (f_right - kf) / d : 0.0f;
            }
            row[k] = val;
        }
    }
}

/* ══════════════════════════════════════════════════════════════════
 * INTERNAL: build orthonormal DCT-II matrix
 * Matches mfcc_core.c build_dct_matrix() exactly.
 * ══════════════════════════════════════════════════════════════════ */
static void build_dct_matrix(void)
{
    const float inv_N  = sqrtf(1.0f / (float)MFCC_N_MEL);
    const float inv_2N = sqrtf(2.0f / (float)MFCC_N_MEL);
    const float pi     = 3.14159265358979323846f;

    for (int k = 0; k < MFCC_N_MFCC; k++) {
        float *row   = s_dct + k * MFCC_N_MEL;
        float  scale = (k == 0) ? inv_N : inv_2N;
        for (int n = 0; n < MFCC_N_MEL; n++) {
            row[n] = scale * cosf(pi * (float)k * (2.0f * (float)n + 1.0f)
                                  / (2.0f * (float)MFCC_N_MEL));
        }
    }
}

/* ══════════════════════════════════════════════════════════════════
 * PUBLIC: dsp_mfcc_init()
 * ══════════════════════════════════════════════════════════════════ */
int dsp_mfcc_init(void)
{
    arm_biquad_cascade_df2T_init_f32(
        &s_bp_inst, BP_N_STAGES,
        (float32_t *)s_bp_coeffs, s_bp_state);

    build_hamming();
    build_mel_filterbank();
    build_dct_matrix();

    arm_status st = arm_rfft_fast_init_f32(&s_rfft, MFCC_FFT_SIZE);
    if (st != ARM_MATH_SUCCESS) {
        LOG_ERR("arm_rfft_fast_init_f32 failed (status=%d)", (int)st);
        return -1;
    }

    LOG_INF("DSP+MFCC init OK: bp@8kHz → ÷4 → 2kHz → MFCC(%d,%d,%d)",
            MFCC_FRAME_SAMPLES, MFCC_N_MEL, MFCC_N_MFCC);
    return 0;
}

/* ══════════════════════════════════════════════════════════════════
 * PUBLIC: dsp_mfcc_reset()
 * Call once before each new recording session.
 * ══════════════════════════════════════════════════════════════════ */
void dsp_mfcc_reset(void)
{
    memset(s_bp_state, 0, sizeof(s_bp_state));
    s_dec_idx = 0;
}

/* ══════════════════════════════════════════════════════════════════
 * PUBLIC: dsp_mfcc_feed_chunk()
 * Bandpass + decimate one SAADC half-buffer into s_decimated[].
 * Call from saadc_event_handler for each NRFX_SAADC_EVT_DONE.
 * ══════════════════════════════════════════════════════════════════ */
void dsp_mfcc_feed_chunk(const int16_t *pcm_8k, int n)
{
    /* Clamp to scratch buffer size just in case */
    if (n > BP_SCRATCH_MAX) {
        n = BP_SCRATCH_MAX;
    }

    /* int16 → float32 */
    for (int i = 0; i < n; i++) {
        s_bp_scratch[i] = (float32_t)pcm_8k[i] / 32768.0f;
    }

    /* Bandpass in-place (state carries over between chunks) */
    arm_biquad_cascade_df2T_f32(&s_bp_inst, s_bp_scratch, s_bp_scratch,
                                (uint32_t)n);

    /* Decimate ÷4 → int16 into s_decimated[] */
    for (int i = 0; i < n; i += DSP_DECIMATE_FACTOR) {
        if (s_dec_idx < DECIMATED_SAMPLES) {
            s_decimated[s_dec_idx++] = (int16_t)(s_bp_scratch[i] * 32768.0f);
        }
    }
}

/* ══════════════════════════════════════════════════════════════════
 * INTERNAL: compute one MFCC frame from int16 signal at 2 kHz.
 * @param sig_2k   Pointer to frame start in s_decimated[].
 * @param out_f32  Output: MFCC_N_MFCC floats written to s_mfcc_frame[].
 * ══════════════════════════════════════════════════════════════════ */
static void compute_one_frame(const int16_t *sig_2k, float32_t *out_f32)
{
    /* Step 1: int16→float32, apply Hamming window, zero-pad to FFT size */
    for (int i = 0; i < MFCC_FRAME_SAMPLES; i++) {
        s_fft_in[i] = ((float32_t)sig_2k[i] / 32768.0f) * s_hamming[i];
    }
    memset(s_fft_in + MFCC_FRAME_SAMPLES, 0,
           (MFCC_FFT_SIZE - MFCC_FRAME_SAMPLES) * sizeof(float32_t));

    /* Step 2: RFFT — output is interleaved Re/Im, Nyquist in slot [1] */
    arm_rfft_fast_f32(&s_rfft, s_fft_in, s_fft_out, 0);

    /* Step 3: power spectrum Re²+Im²
     * CMSIS rfft_fast layout: [DC_re, Nyq_re, re1, im1, re2, im2, ...] */
    s_power[0]                = s_fft_out[0] * s_fft_out[0];
    s_power[MFCC_N_FFT_BINS - 1] = s_fft_out[1] * s_fft_out[1];
    for (int k = 1; k < MFCC_N_FFT_BINS - 1; k++) {
        float32_t re = s_fft_out[2 * k];
        float32_t im = s_fft_out[2 * k + 1];
        s_power[k] = re * re + im * im;
    }

    /* Step 4: mel filterbank dot products */
    for (int m = 0; m < MFCC_N_MEL; m++) {
        float32_t  energy = 0.0f;
        const float32_t *row = s_mel_fb + m * MFCC_N_FFT_BINS;
        for (int k = 0; k < MFCC_N_FFT_BINS; k++) {
            energy += row[k] * s_power[k];
        }
        /* Step 5: log with floor */
        s_mel[m] = logf(energy > 1e-6f ? energy : 1e-6f);
    }

    /* Step 6: DCT-II */
    for (int k = 0; k < MFCC_N_MFCC; k++) {
        float32_t  c   = 0.0f;
        const float32_t *row = s_dct + k * MFCC_N_MEL;
        for (int n = 0; n < MFCC_N_MEL; n++) {
            c += row[n] * s_mel[n];
        }
        out_f32[k] = c;
    }
}

/* ══════════════════════════════════════════════════════════════════
 * PUBLIC: dsp_mfcc_finish()
 *
 * After recording is done (all chunks fed), compute MFCC frames
 * from s_decimated[] and invoke cb() once per frame.
 * No large output buffer needed — s_mfcc_frame[20] is reused each time.
 * ══════════════════════════════════════════════════════════════════ */
int dsp_mfcc_finish(dsp_mfcc_frame_cb_t cb)
{
    if (!cb) {
        LOG_ERR("dsp_mfcc_finish: callback is NULL");
        return -1;
    }

    LOG_INF("Bandpass+decimate done: %d samples at 2 kHz", s_dec_idx);

    int n_frames = 0;

    for (int f = 0; f < MFCC_N_FRAMES; f++) {
        int start = f * MFCC_HOP_SAMPLES;
        if (start + MFCC_FRAME_SAMPLES > s_dec_idx) {
            LOG_WRN("MFCC: ran out of samples at frame %d (start=%d, dec_idx=%d)",
                    f, start, s_dec_idx);
            break;
        }

        compute_one_frame(&s_decimated[start], s_mfcc_frame);
        cb(f, s_mfcc_frame);
        n_frames++;
    }

    LOG_INF("MFCC done: %d frames × %d coefficients", n_frames, MFCC_N_MFCC);
    return n_frames;
}