/**
 * heart_mfcc_config.h
 * ===================
 * Flash-constant table declarations and static config for the HEART pipeline.
 *
 * Heart MFCC parameters (from heart_winning_config.json):
 *   target_rate  = 2000 Hz  (decimate /4 from 8 kHz)
 *   frame_ms     = 25 ms    -> frame_samples = 50
 *   hop_pct      = 0.30     -> hop_samples   = 15
 *   fft_size     = 512      -> n_fft_bins    = 257
 *   num_mel      = 25
 *   num_mfcc     = 25
 *   n_frames     = 1 + (20000 - 50) / 15 = 1331  (10 s @ 2 kHz)
 *   bandpass     = 10-200 Hz Butterworth-4 @ 8 kHz
 *   mel f_low    = 10 Hz, f_high = 1000 Hz (Nyquist of 2 kHz)
 *
 * The actual array contents are in src/generated/heart_mfcc_tables.c,
 * which is auto-generated by tools/gen_mfcc_tables.py. DO NOT hand-edit
 * the generated file.
 */

#ifndef HEART_MFCC_CONFIG_H
#define HEART_MFCC_CONFIG_H

#include "dsp_mfcc.h"
#include <arm_math.h>

/* Flash-constant tables -- generated by tools/gen_mfcc_tables.py */
extern const float32_t heart_bp_coeffs[BP_N_STAGES * 5]; /* SOS 10-200 Hz @ 8 kHz */
extern const float32_t heart_hamming[50];                 /* frame_samples = 50 */
extern const float32_t heart_mel_fb[20 * 257];            /* n_mel * n_fft_bins */
extern const float32_t heart_dct[20 * 20];                /* n_mfcc * n_mel */

/* Static config -- points to flash tables above */
extern const dsp_mfcc_config_t heart_mfcc_config;

#endif /* HEART_MFCC_CONFIG_H */
