/**
 * lung_mfcc_config.h
 * ==================
 * Flash-constant table declarations and static config for the LUNG pipeline.
 *
 * Lung MFCC parameters (from lung_winning_config.json):
 *   target_rate  = 4000 Hz  (decimate /2 from 8 kHz)
 *   frame_ms     = 25 ms    -> frame_samples = 100
 *   hop_pct      = 0.05     -> hop_samples   = 5
 *   fft_size     = 512      -> n_fft_bins    = 257
 *   num_mel      = 13
 *   num_mfcc     = 13
 *   n_frames     = 1 + (40000 - 100) / 5 = 7981  (10 s @ 4 kHz)
 *   bandpass     = 100-1000 Hz Butterworth-4 @ 8 kHz
 *   mel f_low    = 100 Hz, f_high = 2000 Hz (Nyquist of 4 kHz)
 *
 * NOTE ON BANDPASS: user-confirmed 100-1000 Hz (not 1500 Hz as in the
 * original instructions draft). The gen_mfcc_tables.py invocation and
 * the generated lung_mfcc_tables.c both use 100-1000 Hz.
 *
 * WARNING ON LUNG N_FRAMES: 7981 frames x 13 coefficients x 4 bytes
 * = ~415 KB if materialized in RAM. Lung MFCC is streamed frame-by-frame
 * to SD via the callback; no matrix buffering in RAM.
 *
 * The actual array contents are in src/generated/lung_mfcc_tables.c,
 * auto-generated by tools/gen_mfcc_tables.py. DO NOT hand-edit.
 */

#ifndef LUNG_MFCC_CONFIG_H
#define LUNG_MFCC_CONFIG_H

#include "dsp_mfcc.h"
#include <arm_math.h>

/* Flash-constant tables -- generated by tools/gen_mfcc_tables.py */
extern const float32_t lung_bp_coeffs[BP_N_STAGES * 5]; /* SOS 100-1000 Hz @ 8 kHz */
extern const float32_t lung_hamming[1200];      /* frame_samples = 1200 */
extern const float32_t lung_mel_fb[26 * 1025];  /* n_mel * n_fft_bins */
extern const float32_t lung_dct[26 * 26];       /* n_mfcc * n_mel */

/* Static config -- points to flash tables above */
extern const dsp_mfcc_config_t lung_mfcc_config;

#endif /* LUNG_MFCC_CONFIG_H */
