/**
 * lung_mfcc_config.h
 * ==================
 * Flash-constant table declarations and static config for the LUNG pipeline.
 *
 * v2 — comments synced to actual generated tables and winning config.
 *
 * Lung MFCC parameters (from lung_winning_config.json — CURRENT):
 *   target_rate  = 4000 Hz  (decimate /2 from 8 kHz)
 *   frame_ms     = 300 ms   -> frame_samples = 1200
 *   hop_pct      = 0.10     -> hop_samples   = 120
 *   fft_size     = 2048     -> n_fft_bins    = 1025
 *   num_mel      = 26
 *   num_mfcc     = 26
 *   n_frames     = 1 + (40000 - 1200) / 120 = 324  (10 s @ 4 kHz)
 *   bandpass     = 100-1000 Hz Butterworth-4 @ 8 kHz
 *
 * The actual array contents are in src/generated/lung_mfcc_tables.c,
 * auto-generated by tools/gen_mfcc_tables.py. DO NOT hand-edit.
 *
 * If you regenerate the tables with different parameters, you MUST
 * update both the array dimensions below AND the lung_mfcc_config
 * struct values in lung_mfcc_tables.c (or wherever the struct is
 * defined). dsp_mfcc_init() validates the config at runtime and will
 * fail loudly if the dimensions disagree with the compiled-in
 * scratch buffer limits (MAX_FFT_SIZE etc. in dsp_mfcc.c).
 */

#ifndef LUNG_MFCC_CONFIG_H
#define LUNG_MFCC_CONFIG_H

#include "dsp_mfcc.h"
#include <arm_math.h>

/* Flash-constant tables -- generated by tools/gen_mfcc_tables.py */
extern const float32_t lung_bp_coeffs[BP_N_STAGES * 5]; /* SOS 100-1000 Hz @ 8 kHz */
extern const float32_t lung_hamming[1200];               /* frame_samples = 1200 */
extern const float32_t lung_mel_fb[26 * 1025];           /* n_mel * n_fft_bins */
extern const float32_t lung_dct[26 * 26];                /* n_mfcc * n_mel */

/* Static config -- points to flash tables above */
extern const dsp_mfcc_config_t lung_mfcc_config;

#endif /* LUNG_MFCC_CONFIG_H */